RailsDeviseApp/config/routes.rb
Rails.application.routes.draw do
  get 'blogs', to: 'blogs#index'
  get 'blogs/index'
  get 'blogs/:page', to: 'blogs#index'

  get 'blogs/genre/:id', to: 'blogs#genre'
  get 'blogs/genre/:id/:page', to: 'blogs#genre'

  get 'blogs/show/:id', to: 'blogs#show'

  get 'blogposts/index'
  get 'blogposts', to: 'blogposts#index'

  get 'blogposts/delete/:id', to: 'blogposts#delete'
  post 'blogposts/delete', to: 'blogposts#delete'
  post 'blogposts/delete/:id', to: 'blogposts#delete'

  get 'blogposts/add'
  post 'blogposts/add'

  get 'blogposts/:id', to: 'blogposts#edit'
  patch 'blogposts/:id', to: 'blogposts#edit'

  get 'blogposts/delete'

  get 'bloggenres/index'
  get 'bloggenres', to: 'bloggenres#index'

  get 'bloggenres/add'
  post 'bloggenres/add'

  get 'blogsgenres/:id', to: 'bloggenres#edit'
  patch 'bloggenres/:id', to: 'bloggenres#edit'

  get 'blogconfigs', to: 'blogconfigs#index'
  get 'blogconfigs/index'
  
  get 'blogconfigs/edit'
  patch 'blogconfigs/edit'
  resources :board_comments
  resources :board_messages
  resources :board_users
  resources :data_pages
  get 'hello/index'
  get 'hello/login_check'
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

RailsDeviseApp/app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

RailsDeviseApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RailsDeviseApp/app/models/blogconfig.rb
class Blogconfig < ApplicationRecord
    validates :title, :stylename, presence: {message:'は，必須項目です．'}
end

RailsDeviseApp/app/models/bloggenre.rb
class Bloggenre < ApplicationRecord
    has_many :blogpost

    validates :name, presence: {message:'は，必須項目です．'}
end

RailsDeviseApp/app/models/blogpost.rb
class Blogpost < ApplicationRecord
    belongs_to :bloggenre
    has_rich_text :content #contetにAction Textを設定
    
    validates :title, :content, presence: {message:'は，必須項目です．'}
end

RailsDeviseApp/app/models/board_comment.rb
class BoardComment < ApplicationRecord
    belongs_to :board_user

    validates :content, presence: {message:'は，必須項目です．'}
end

RailsDeviseApp/app/models/board_message.rb
class BoardMessage < ApplicationRecord
    belongs_to :board_user

    validates :content, presence: {message:'は，必須項目です．'}
end

RailsDeviseApp/app/models/board_user.rb
class BoardUser < ApplicationRecord
    belongs_to :account
    has_many :board_comment

    validates :nickname, presence: {message:'は，必須項目です．'}
end

RailsDeviseApp/app/models/data_page.rb
class DataPage < ApplicationRecord
end

RailsDeviseApp/app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  layout 'blog'

  def index
    @data = Blogpost.all.order('created_at desc')
  end

  def add
    @blogpost = Blogpost.new
    @genres = Bloggenre.all
    if request.post? then
      @blogpost = Blogpost.create blogposts_params
      redirect_to '/blogposts'
    end
  end

  def edit
    @blogpost = Blogpost.find params[:id]
    @genres = Bloggenre.all
    if request.patch? then
      @blogpost.update blogposts_params
      redirect_to '/blogposts'
    end
  end

  def delete
    @blogpost = Blogpost.find(params[:id])
    if request.post? then
      @blogpost.destroy
      redirect_to '/blogposts'
    end
  end

  private
  def blogposts_params
    params.require(:blogpost).permit(:title, :read, :content, :bloggenre_id)
  end
end

RailsDeviseApp/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  layout 'blogs'

  def index
    @data = Blogpost.order('created_at desc').page params[:page]
    @blogconfig = Blogconfig.find 1
  end

  def genre
    @genre = Bloggenre.find params[:id]
    @data = Blogpost.where('bloggenre_id = ?',params[:id]).order('created_at desc').page params[:page]
    @blogconfig = Blogconfig.find 1
  end

  def show
    @blogpost = Blogpost.find params[:id]
    @blogconfig = Blogconfig.find 1
  end
end

RailsDeviseApp/app/controllers/board_users_controller.rb
class BoardUsersController < ApplicationController
  before_action :set_board_user, only: %i[ show edit update destroy ]
  before_action :authenticate_account!
  # layout 'board_users' #必要に応じて用意

  # GET /board_users or /board_users.json
  def index
    users = BoardUser.where 'account_id == ?', current_account.id
    if users[0] == nil then
      user = BoardUser.new
      user.account_id = current_account.id
      user.nickname = '<<no name>>'
      user.save
      users = BoardUser.where 'account_id == ?', current_account.id
    end
    @board_user = users[0]
  end

  # GET /board_users/1 or /board_users/1.json
  def show
    @board_user = BoardUser.find params[:id]
  end

  # GET /board_users/new
  def new
    redirect_to '/board_comments'
  end

  # GET /board_users/1/edit
  def edit
    redirect_to '/board_comments'
  end

  # POST /board_users or /board_users.json
  def create
    redirect_to '/board_comments'
  end

  # PATCH/PUT /board_users/1 or /board_users/1.json
  def update
    respond_to do |format|
      if @board_user.update(board_user_params)
        format.html { redirect_to '/board_comments' }
        format.json { render :show, status: :ok, location: @board_user }
      else
        format.html { render :index }
        format.json { render json: @board_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /board_users/1 or /board_users/1.json
  def destroy
    redirect_to '/board_comments'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board_user
      @board_user = BoardUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_user_params
      params.require(:board_user).permit(:nickname, :account_id, :memo)
    end
end

RailsDeviseApp/app/controllers/hello_controller.rb
class HelloController < ApplicationController
  layout 'application'
  before_action :authenticate_account!, only: :login_check
  #ログイン必須に設定（authenticate_(モデル名)!はDeviceを組み込めば自動で追加されるメソッド）
  #モデル名に入るのは，「rails generate device モデル名」で作成したモデル
  def index
    @msg = 'this is sample page.'
  end

  def login_check
    @account = current_account
    #current_モデル名 は，ログインしている利用者のAccountインスタンスが返ってくる
    @msg = 'account created at: ' + @account.created_at.to_s
  end
end

RailsDeviseApp/app/helpers/application_helper.rb
module ApplicationHelper
end

RailsDeviseApp/app/helpers/blogconfigs_helper.rb
module BlogconfigsHelper
end

RailsDeviseApp/app/helpers/bloggenres_helper.rb
module BloggenresHelper
end

RailsDeviseApp/app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

RailsDeviseApp/app/helpers/blogs_helper.rb
module BlogsHelper
end

RailsDeviseApp/app/helpers/board__messages_helper.rb
module BoardMessagesHelper
end

RailsDeviseApp/app/helpers/board_comments_helper.rb
module BoardCommentsHelper
end

RailsDeviseApp/app/helpers/board_users_helper.rb
module BoardUsersHelper
end

RailsDeviseApp/app/helpers/data_pages_helper.rb
module DataPagesHelper
end

RailsDeviseApp/app/helpers/hello_helper.rb
module HelloHelper
end

RailsDeviseApp/app/views/board_users/_form.html.erb
<%= form_with(model: board_user, local: true) do |form| %>
  <% if board_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board_user.errors.count, "error") %> prohibited this board_user from being saved:</h2>

      <ul>
        <% board_user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :account_id %>

  <div class="form-group">
    <%= form.label :nickname %>
    <%= form.text_field :nickname, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :account_id %>
    <div class="border p-1">
      <%=@board_user.account_id %>
    </div>
    <%= form.hidden_field :account_id %>
  </div>

  <div class="form-group">
    <%= form.label :memo %>
    <%= form.text_area :memo, class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RailsDeviseApp/app/views/board_users/edit.html.erb
<h1>Editing Board User</h1>

<%= render 'form', board_user: @board_user %>

<%= link_to 'Show', @board_user %> |
<%= link_to 'Back', board_users_path %>

RailsDeviseApp/app/views/board_users/index.html.erb
<h1 class="display-4 text-primary">User Home</h1>

<h2 class=="h4">※<%=@board_user.account.email %> さんの設定</h2>
<%= render 'form', board_user: @board_user %>
<hr>
<p><%=link_to '<< go back', controller: :board_comments %></p>

<hr>
<div>copyright SYODA-Tuyano 2020.</div>

RailsDeviseApp/app/views/board_users/new.html.erb
<h1>New Board User</h1>

<%= render 'form', board_user: @board_user %>

<%= link_to 'Back', board_users_path %>

RailsDeviseApp/app/views/board_users/show.html.erb
<h1 class="display-4 text-primary"><%=@board_user.nickname %></h1>

<table class="table">
  <tr>
    <th>Nickname</th>
    <td><%= @board_user.nickname %></td>
  </tr>
  <tr>
    <th>Id</th>
    <td><%= @board_user.id %></td>
  </tr>
  <tr>
    <th>Created at</th>
    <td><%= @board_user.created_at %></td>
  </tr>
  <tr>
    <th>Memo</th>
    <td><%= @board_user.memo %></td>
  </tr>
</table>

<hr>
<%= link_to '<< Back', controller: :board_comments %>
<hr>
<div>copyright SYODA-Tuyano 2020.</div>