RailsApp/config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  resources :mycontacts
  get 'messages/index'
  get 'messages', to: 'messages#index'

  get 'messages/add'
  post 'messages/add', to: 'messages#create'

  get 'messages/edit/:id', to: 'messages#edit'
  patch 'messages/edit/:id', to: 'messages#update'

  get 'messages/delete/:id', to: 'messages#delete'
  get 'messages/:id', to: 'messages#show'
  get 'cards/index'
  get 'cards', to: 'cards#index'

  get 'cards/show'

  get 'cards/add'
  post 'cards/add'

  get 'cards/:id', to: 'cards#show'

  get 'cards/edit/:id', to: 'cards#edit'
  patch 'cards/edit/:id', to: 'cards#edit'

  get 'cards/delete/:id', to: 'cards#delete'

  get 'people/index'
  get 'msgboard', to: 'msgboard#index'
  post 'msgboard', to: 'msgboard#index'
  get 'msgboard/index'
  post 'msgboard/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello/index'
  get 'hello', to: 'hello#index'
  get 'hello/other'
  post 'hello', to: 'hello#index'
  post 'hello/index'

  get 'people', to: 'people#index'
  get 'people/add'
  post 'people/add', to: 'people#create'

  get 'people/edit/:id', to: 'people#edit'
  post 'people/edit/:id', to: 'people#update'
  patch 'people/edit/:id', to: 'people#update'

  get 'people/delete/:id', to: 'people#delete'

  get 'people/find'
  post 'people/find'

  get 'people/:id', to: 'people#show'
end

RailsApp/app/models/question.rb
class Question < ApplicationRecord
    has_many :answer
    
    validates :content, :name, presence: {message:'は，必須項目です．'}
end

RailsApp/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy ]
  layout 'Q&A'

  # GET /questions or /questions.json
  def index
    @questions = Question.all.order created_at: :desc
  end

  # GET /questions/1 or /questions/1.json
  def show
    @answer = Answer.new
    @answer.question_id = params[:id]
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    redirect_to '/questions'
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to '/questions' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    redirect_to '/questions'
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    redirect_to '/questions'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:title, :content, :name, :finished)
    end
end

RailsApp/app/helpers/questions_helper.rb
module QuestionsHelper
end

RailsApp/app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, rows:5, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <%= form.hidden_field :finished, { value:false } %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RailsApp/app/views/questions/_form2.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<%= form.hidden_field :question_id, {value: answer.question_id} %>
	
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, rows:2, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RailsApp/app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

RailsApp/app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4 text-primary">Questions</h1>

<table class="table mt-5 mb-5">
  <thead>
    <tr>
      <th>Title</th>
      <th>Finished</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.finished ? '終了' : '受付中' %></td>
        <td><%= link_to 'Show', question %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '※新たに質問する', new_question_path %>

RailsApp/app/views/questions/new.html.erb
<h1 class="display-4 text-primary">New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

RailsApp/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4 text-primary">Question & Answers</h1>

<div class="jumbotron p-4 mb-4">
  <h2 class="card-title">
    <%= @question.title %>
  </h2>
  <p class="card-text">
    <%= @question.content %>
  </p>
  <p class="blockquote-footer text-right">
    <%= @question.name %>
  </p>
  <div class="<%= @question.finished ? 'text-danger' : 'text-primary' %>">
    <%= @question.finished ? '終了' : '受付中' %>
  </div>
</div>

<% if @question.finished? == false then %>
  <div class="card p-3 mb-4">
    <h3 class="h4 text-primary">※回答する</h3>
    <%= render 'form2', answer: @answer %>
  </div>
<% end %>

<h3 class="h4 text-primary">※これまで寄せられた回答</h3>

<ul class="list-group">
<% if @question.answer.count == 0 then %>
  <p class="answer">※まだありません．</p>
<% else %>
  <% @question.answer.reverse_each do |re| %>
    <li class="list-group-item">
      <%= re.content + '（' + re.name + '）' %>
    </li>
  <% end %>
<% end %>
</ul>

<%= link_to 'Back', questions_path %>